name: Java Build and Test

stages:
  - name: Build
    tasks:
      - name: Maven Build
        plugin: Maven 3
        configuration:
          goals: clean install
          workingSubDirectory: .
  
  - name: Test
    tasks:
      - name: Run SonarQube Tests
        plugin: SonarQube Scanner
        configuration:
          sonarQubeProjectName: Java Project
          sonarQubeProjectKey: Java_Project
          sonarQubeProjectVersion: 1.0
          sonarQubeScannerJavaOpts: -Xmx1024m
          sonarQubeScannerLoggingLevel: WARNING

  - name: Artifacts
    tasks:
      - name: Save Build Artifacts
        plugin: Artifact Download
        configuration:
          artifactDefinition:
            type: buildResult
            pattern: '*/'
